### ISSUE TITLE
option to enable /disable auto-launch spotify after install

### ISSUE THREAD

**Issue by bachig26** [Protonosgit/Spicetify_Installer#17]
**Describe the feature**

personally i don't want the spotify to launch automatically right after the spicetify install, since i find the manual launch button that you have made works fine for me at my terms.

**Comment by Protonosgit** [comment]
I can add an option for that in the next release

**Comment by Protonosgit** [comment]
The restart of Spotify is related to the installation of the Marketplace and will only happen if the program is installed and **not** while updating or other actions.
All other restarts are automatically supressed using the -n flag which are 90% of all command actions.
While I also dislike this function it is built in to the Maketplace setup script and not part of this Manager which means it cannot be deactivated.
I'll try to find a solution to this but keep in mind that some restarts are required in order to guarantee a successful installation!

**Comment by Protonosgit** [comment]
Maybe in 1.3.0

**Comment by Protonosgit** [comment]
#23

**Comment by Protonosgit** [comment]
Should work for most actions exept the install marketplace action (includes first setup)
